name: Deploy Storecle
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@gluecodes'
      - run: yarn install --production=false
      - run: yarn lint
      - run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg ca-certificates
          sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install libxss1
          sudo apt-get install -y google-chrome-stable
          sudo rm -rf /var/lib/apt/lists/*
          sudo wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh
          sudo chmod +x /usr/sbin/wait-for-it.sh
      - run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - run: yarn start & sleep 5 && yarn test
        working-directory: ./test/env/react
      - run: yarn start & sleep 5 && yarn test
        working-directory: ./test/env/solid
      - run: echo $(jq -s '.[0] * .[1]' package.json packageProdOverrides-react.json) > package.json
      - run: npm publish
      - run: echo $(jq -s '.[0] * .[1]' package.json packageProdOverrides-solid.json) > package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
